// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwqi0ELpsvUrVdLu0DEjxhy86dcFVbH6A',
    appId: '1:304192294041:web:a0929a708c0fa3473a7c08',
    messagingSenderId: '304192294041',
    projectId: 'iskissors-m-app',
    authDomain: 'iskissors-m-app.firebaseapp.com',
    storageBucket: 'iskissors-m-app.firebasestorage.app',
    measurementId: 'G-Y7KE3YGHYX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ7rh8Vky_Bq2ISr3KyrMXoFAMhIHa_Qk',
    appId: '1:304192294041:android:b8610952293fbffd3a7c08',
    messagingSenderId: '304192294041',
    projectId: 'iskissors-m-app',
    storageBucket: 'iskissors-m-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3aSNHsh9m4aOJmKCXN87_0AcN2BW969k',
    appId: '1:304192294041:ios:a763516d60d8bec83a7c08',
    messagingSenderId: '304192294041',
    projectId: 'iskissors-m-app',
    storageBucket: 'iskissors-m-app.firebasestorage.app',
    iosBundleId: 'com.example.iskissorsApp',
  );
}
